### ISSUE TITLE
Upgrade Rosetta (Modular, ES6+, React, String Improvements)

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#272]
To keep the Git history of both the old Rosetta and the new Rosetta rewrite, we will need to create a branch and merge the branch. See https://stackoverflow.com/a/1684694.

**Comment by liam-mulhall** [comment]
Also see https://stackoverflow.com/a/32684503.

**Comment by liam-mulhall** [comment]
# Milestones

- [ ] Add functionality to save strings to Babel. (date completed = )
- [ ] Add test button and associated functionality. (date completed = )
- [ ] Make footer stick to the bottom. (date completed = )
- [ ] Add form validation equivalent to what current Rosetta has. (date completed = )
- [ ] At this point, the new Rosetta is equivalent to the old Rosetta. (date completed = )
- [ ] Add translation report. (date completed = )
- [ ] Meet with MP to discuss integrating Rosetta into the website. (date completed = )
- [ ] Integrate Rosetta into website (deploy to Ox-Dev). (date completed = )
- [ ] Meet with designers and/or ON to discuss UI/UX and log and prioritize GH issues. (date completed = )
- [ ] Dev test Ox-Dev version and log and prioritize issues. (date completed = ) 
- [ ] Address issues / more QA. (date completed = )
- [ ] Merge Liam's fork into phetsims/rosetta repo. (date completed = )
- [ ] Deploy. (date completed = )
