### ISSUE TITLE
Rosetta 2.0: Modularize code, use modern JavaScript, use React for front end, add translation report

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#284]
# Rosetta 2.0

This is an epic issue to track the refactor of Rosetta.

## 1: Transfer code from my fork to this repository, add lint rule, separate client and source code using NPM workspaces

I want to integrate my fork ([liam-mulhall/rosetta](https://liam-mulhall/rosetta)) of [phetsim/rosetta](https://github.com/phetsims/rosetta) back into phetsims/rosetta.

- [x] https://github.com/phetsims/rosetta/issues/265
- [x] https://github.com/phetsims/rosetta/issues/287
- [x] Separate client and source code using NPM workspaces (do this on the `rosetta_2.0_rev2` branch) (done in https://github.com/phetsims/rosetta/commit/3776b92c73cf2bca23078af65c916e1f22bd3edc)

(Originally, we planned to create a new branch and transfer the code more or less manually, but we instead decided to transfer the code by rebasing my fork onto the phetsims/rosetta master branch and then creating a new branch `liam_fork` in this repo. There were other steps in this section.)

## 2: Add old Rosetta features to Rosetta 2.0

We want Rosetta 2.0 to have the exact same features as the old Rosetta.

- [x] https://github.com/phetsims/rosetta/issues/298
- [x] https://github.com/phetsims/rosetta/issues/278
- [x] https://github.com/phetsims/rosetta/issues/306
- [x] https://github.com/phetsims/rosetta/issues/297
- [x] https://github.com/phetsims/rosetta/issues/296
- [x] https://github.com/phetsims/rosetta/issues/288
- [x] https://github.com/phetsims/rosetta/issues/289
- [x] Add module for sending build requests to the build server
- [x] Add trigger build route
- [x] Add RTL support
- [x] Investigate missing English strings (related to e70bf1bb2f67a390a092bd31b018cbca4db09a1b or 592c0d8a10a015c1e00dd42dc66a16abdd9e17d6?)
  - [x] discuss with JB and see if we need to fix something
- [x] get SHA of published version of sim from sim HTML so that you can get the correct string file
- [x] Add module for requesting a trigger build
- [x] Figure out when and where to get session data for Rosetta (custom hooks? context?)
  - [x] When/where should we be getting sim names and sim titles?
  - [x] When/where should be be getting check-login info (website user data)?
- [x] display sim title on translation form page
- [x] run Rosetta 2.0 on Windows, fix any weird issues that might come up
- [x] audit code, look for anything that should be refactored
- [x] rename anything poorly named
- [x] add Grunt task for installing all dependencies (chipper, perennial, perennial-alias, etc.)
- [x] https://github.com/phetsims/rosetta/issues/295

## 3: Finalize design of Rosetta 2.0

We want a "translation report" that gives translators some statistics about which sims in their locale have been translated, how complete the translation is, etc.

Before we start work on the translation report in earnest, we need to decide on the behavior, features, user interface, and overall design of the translation report.

- [x] https://github.com/phetsims/rosetta/issues/290

## 4: Add translation report and other new features to Rosetta 2.0

Once we've finalized the design of the translation report, we'll need to implement the translation report.

~~- [ ] https://github.com/phetsims/rosetta/issues/317~~
- [x] https://github.com/phetsims/rosetta/issues/163
- [x] Add build script to `Gruntfile.cjs`.
- [x] https://github.com/phetsims/rosetta/issues/299
- [x] https://github.com/phetsims/rosetta/issues/305
- [x] Use website data to determine which sims have translations and which sims don't have translations
- [x] For each sim that has a translation, get:
  - [x] the total number of strings in the published sim
  - [x] the total number of strings translated for that sim
- [x] Store this data in memory or in a database (otherwise it would take too long to build a translation report)
- [x] Create the back end infrastructure needed to send this data to the front end
- [x] Create a user interface that can display this data
- [x] https://github.com/phetsims/rosetta/issues/300

## 5: Integrate Rosetta 2.0 with the website

We need to figure out how Rosetta 2.0 will be situated within the PhET website. It would be ideal if we could "soft deploy" Rosetta 2.0 to phet-server-dev (which I believe is https://ox-dev.colorado.edu) before we hand Rosetta 2.0 over to QA for testing.

- [x] Meet with MP to discuss integrating Rosetta 2.0 into the website
- [x] Deploy Rosetta 2.0 to phet-server-dev (https://ox-dev.colorado.edu)

## 6: Test Rosetta 2.0

Once the above stages have been completed, we'll need to hand Rosetta 2.0 over to QA for manual testing. We'll then need to address the issues that come up during testing.

- [x] Write up GitHub issue in [phetsims/qa](https://github.com/phetsims/qa)
- [x] Address issues that come up in testing

## 7: Wrap up and deploy Rosetta 2.0

Once we've resolved the issues that come up during testing, we should merge the `rosetta_2.0_main` branch into Rosetta's `master` branch and deploy Rosetta 2.0 to phet-server (https://phet.colorado.edu).

- [x] Merge the `rosetta_2.0_main` branch into the phetsims/rosetta master branch
- [x] Review issues in this repository and either close or update them
- [x] Deploy Rosetta 2.0 to phet-server (https://phet.colorado.edu)

**Comment by liammulh** [comment]
Rosetta 2.0 was deployed on the 21st of February. Closing.
